### ISSUE TITLE
create user model

### ISSUE THREAD

**Issue by IzumiShaka-desu** [IzumiShaka-desu/pmb_tugas#1]
# Overview
@Tevan13 will create user model for user entity database interaction, table "user" have 6 properties : 
- IDUser	
- Nama	
- Password (use sha1 encrypt)
- Hak_Akses	
- Manager	
- Create_Date	

## Features
- [x] create user account  ➕ 
- [x] update user account ✏️
- [x] read user account list 👀 
- [x] delete user account ❌  
### References
- [https://medanincode.com/post/ci4/membuat-grafik-dari-database-codeigniter-4/](https://medanincode.com/post/ci4/membuat-grafik-dari-database-codeigniter-4/)

**Comment by Tevan13** [comment]
Tolong Diperiksa Senpai ^-^ !
