### ISSUE TITLE
create Motor Gallery  view

### ISSUE THREAD

**Issue by IzumiShaka-desu** [IzumiShaka-desu/pmb_tugas#15]
# Overview
where can display motor details, table "identitas_motor " have properties :
- ID(Integer),
-  NoRegistrasi,
-  NamaPemilik,
-  Alamat,
-  NoRangka,
-  NoMesin,
-  PlatNO,
-  Merk,
-  Type,
-  Model,
- TahunPembuatan,
-  IsiSilinder,
-  BahanBakar,
-  WarnaTNKB,
-  TahunRegistrasi,
-  NoBPKB,
-  KodeLokasi,
- MasaBerlakuSTNK.
## Features
- [x] create view Gallery motor sale 🛵 
reference :  ![bootstrap-photo-gallery](https://user-images.githubusercontent.com/65596335/146488265-9c498564-11ef-4dcb-83df-0c2a3d587d5e.jpg)

**Comment by Tevan13** [comment]
Ane ini deh

**Comment by Tevan13** [comment]
Aku ini gaes

**Comment by Tevan13** [comment]
selesai dong
